name: podcast_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  accessibility_tools: ^2.7.1
  app_links: ^6.4.1
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.2.0
  extended_image: ^10.0.1
  file_picker: ^10.3.3
  flutter_dialogs: ^3.0.0
  flutter_downloader: ^1.12.0
  flutter_html: ^3.0.0
  flutter_html_svg: ^3.0.0
  flutter_html_table: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.2
  html: ^0.15.6
  intl: ^0.20.2
  intl_translation: ^0.21.0
  just_audio: ^0.10.5
  logging: ^1.3.0
  meta: ^1.16.0
  mp3_info: ^0.2.1
  path: ^1.9.1
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.2
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.8
  sembast: ^3.8.5+1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  xml: ^6.6.1
  mockito: ^5.5.1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Use a temporary, patched version of podcast_search which allows us to use it with an older
  # version of Flutter. This is required due to an accessibility bug in 3.3x and above.
  podcast_search:
    git:
      url: https://github.com/amugofjava/podcast_search.git
      ref: hotfix/flutter_accessibility_regression 
  sliver_tools: ^0.2.12
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  intl: ^0.20.2

flutter_icons:
  image_path_android: "assets/images/anytime-logo.png"
  image_path_ios: "assets/images/anytime-logo-ios.png"
  remove_alpha_ios: true
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png
    - assets/images/anytime-placeholder-logo.png

    # Certificate authorities
    - assets/ca/lets-encrypt-r3.pem
    - assets/ca/globalsign-gcc-r6-alphassl-ca-2023.pem

  fonts:
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
